groups:
- name: 1c_system.rules
  rules:

# alert for instance down
  - alert: InstanceDown
    expr: up{job="1C Servers"} == 0
    for: 10m
    labels:
      severity: warning
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down
        for more than 10 minute.'
      summary: Instance {{ $labels.instance }} down


# alert for services down for more than 
#  - alert: ServiceDown
#    expr: win_services_state{service_name=~".*1C.*",host!~"hq-1c-term|SIT-1C-AS2"} != 4
#    for: 1m
#    labels:
#      severity: warning



# alert for low free space
#  - alert: LowDiskSpace
#    expr: win_disk_Percent_Free_Space{exported_instance=~".*:.*",job="1C Servers"} < 20
#    for: 5m
#    labels:
#      severity: warning
#    annotations:
#      description: '{{ $labels.instance }} of job {{ $labels.job }} has low
#        disk space {{ $value }}%.'
#      summary: Instance {{ $labels.instance }} low free space {{ $value }}%

# alert for low free space
#  - alert: CriticalDiskSpace
#    expr: win_disk_Percent_Free_Space{exported_instance=~".*:.*",job="1C Servers"} < 10                                                                                                    
#    for: 5m
#    labels:
#      severity: warning
#    annotations:
#      description: '{{ $labels.instance }} of job {{ $labels.job }} has low
#        disk space {{ $value }}%.'
#      summary: Instance {{ $labels.instance }} low free space {{ $value }}%



