groups:
- name: print_system.rules
  rules:

# alert for instance down
  - alert: InstanceDown
    expr: up{job="Print Servers"} == 0
    for: 30s
    labels:
      severity: warning
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down
        for more than 1 minute.'
      summary: Instance {{ $labels.instance }} down

# alert for services down for more than 
  - alert: ServiceDown
    expr: win_services_state{service_name="Spooler"} != 4
    for: 30s
    labels:
      severity: warning

