groups:
- name: squid_proxy.rules
  rules:
# alert for instance down
  - alert: InstanceDown
    expr: up{job="Squid proxy system"} == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down
        for more than 1 minute.'
      summary: Instance {{ $labels.instance }} down

# alert for  services down
  - alert: ServiceDown
    expr: node_systemd_unit_state{name=~"glusterd.service|squid.service|keepalived.service|smbd.service|nmbd.service",state="active"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      description: 'proxy service of job {{ $labels.job }} has been down
        for more than 1 minute.'
      summary: proxy service down



# alerts for low disk space
  - alert: Low free disk space
    expr: 100 - ((node_filesystem_avail_bytes{device=~".*vg.*|.*DPC.*",job="Squid proxy system"} * 100) / node_filesystem_size_bytes{device=~".*vg.*|.*DPC.*"}) < 20
    for: 3m
    labels:
      severity: warning
    annotations:
      description: "{{ $labels.instance }} has a low free disk space (current value: {{ $value }})"


# alerts for critical disk space
  - alert: Critical free disk space
    expr: 100 - ((node_filesystem_avail_bytes{device=~".*vg.*|.*DPC.*",job="Squid proxy system"} * 100) / node_filesystem_size_bytes{device=~".*vg.*|.*DPC.*"}) < 10
    for: 30s
    labels:
      severity: critical
    annotations:
      description: "{{ $labels.instance }} has a low free disk space (current value: {{ $value }})"





