groups:
- name: web_sites.rules
  rules:

  - alert: site_down
    expr: probe_success{job="blackbox-http_2xx"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Critical: Site '{{ $labels.instance }}' isn't available for more than 3 minutes"
      description: "Site {{ $labels.instance }} isn't available(down)"
 
  - alert: site_is_very_slow
    expr: sum by (instance) (probe_http_duration_seconds) > 3
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Warning: Site '{{ $labels.instance }}' is very slow(>3s) for more than 3 minutes"
      description: "Site {{ $labels.instance }} response for {{ humanize $value}}s"

  - alert: http_status_code_not_200-299
    expr: probe_http_status_code{instance!=".*10.199.5.6.*"} <= 199 OR probe_http_status_code >= 300
    for: 3m
    labels:
      severity: critical
    annotations:
      summary: "Critical: HTTP status code for the site '{{ $labels.instance }}' isn't 200-299 for more than 3 minutes"
      description: "HTTP status code is {{ $value }}"

  - alert: ssl_certificate_expire#
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 *30
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Warning: SSL certificate will expire soon for the site '{{ $labels.instance }}'"
      description: "SSL certificate expires in 30 days"
