version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - /opt/prometheus/conf:/etc/prometheus
      - /etc/prometheus/data:/etc/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus/data'
      - '--storage.tsdb.retention.size=40GB'
      - '--storage.tsdb.retention.time=120d'
    ports:
      - "9090:9090"
    networks:
      prom_net:
        ipv4_address: 172.20.0.10

  grafana:
    image: grafana/grafana
    user: "0"
    volumes:
      - /opt/grafana/conf/grafana.ini:/etc/grafana/grafana.ini
      - /var/lib/grafana/:/var/lib/grafana
    ports:
      - 3000:3000
    container_name: grafana
    restart: always
    links:
      - prometheus
    networks:
      prom_net:
        ipv4_address: 172.20.0.20

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    container_name: alertmanager
    volumes:
      - /opt/alertmanager/conf:/etc/alertmanager
    restart: always
    links:
      - prometheus
    networks:
      prom_net:
        ipv4_address:  172.20.0.30


networks:
  prom_net:
    ipam:
     config:
       - subnet:  172.20.0.0/24
