- targets:
  - dpc-1c-as1.hq.mosgortrans.com:9273
  - dpc-1c-as2.hq.mosgortrans.com:9273
  - dpc-1c-as3.hq.mosgortrans.com:9273
  - dpc-1c-as4.hq.mosgortrans.com:9273
  - dpc-1c-as5.hq.mosgortrans.com:9273
  - dpc-1c-as6.hq.mosgortrans.com:9273
  - dpc-1c-bd-01.hq.mosgortrans.com:9273
  - dpc-1c-journal.hq.mosgortrans.com:9273
  - dpc-1c-lic.hq.mosgortrans.com:9273
  - dpc-1c-mon.hq.mosgortrans.com:9273
  - dpc-1c-web.hq.mosgortrans.com:9273
#  - dpc-1c-term-01.hq.mosgortrans.com:9273
  - hq-1c-bd2.hq.mosgortrans.com:9273
  - hq-1c-term.hq.mosgortrans.com:9273
  - sit-1c-as2.hq.mosgortrans.com:9273
  - sit-1c-term.hq.mosgortrans.com:9273
  - sit-1c-bd.hq.mosgortrans.com:9273
  - sit-1c-web.hq.mosgortrans.com:9273
