- targets: 

#  ADFS servers
- targets:
  - dpc-adfs-01.hq.mosgortrans.com:9273
  - dpc-adfs-02.hq.mosgortrans.com:9273
  - dpc-azure-01.hq.mosgortrans.com:9273
  labels:
    adfs_servers: 'adfs_windows'



# NGINX servers
- targets:
  - 10.199.0.37:9100      # node_exporter
  - 10.199.0.38:9100
  labels: 
    object: 'node_exporter'
    adfs_servers: 'adfs_nginx'
- targets:
  - 10.199.0.37:8080      # cAdvisor
  - 10.199.0.38:8080
  labels: 
    object: 'cadvisor'
    adfs_servers: 'adfs_nginx'
