- targets:
  - https://cloud.mosgortrans.ru
  - https://kibana.mosgortrans.com
  - https://mail.mosgortrans.com
  - https://teampass.mosgortrans.ru
  - https://gitlab.mosgortrans.ru
  - http://10.100.255.190:9000/stats
